services:
  pgadmin:
    extends: 
      file: docker-compose.yaml
      service: pgadmin
    environment:
      - REQUESTS_CA_BUNDLE=/run/secrets/zscaler
      - SSL_CERT_FILE=/run/secrets/zscaler
    secrets:
      - zscaler

  sysml_v2_pilot_api:
    extends: 
      file: docker-compose.yaml
      service: sysml_v2_pilot_api
    build:
      secrets:
        - zscaler

secrets:
  zscaler:
    file: ${CERT_PATH}
