#!/usr/bin/env python3
"""
make_publish_notebook.py
========================
Generate a clean, headless-runnable ``publish.ipynb`` that publishes the WHOLE
BilgePump model as ONE unified project and evaluates every verification
assertion.

UNIFIED SINGLE-PROJECT PUBLISH (stable UUID)
--------------------------------------------
Earlier the pipeline published each layer as its own project
(``BilgePump_Library``, ``BilgePump_Architecture``, …).  Publishing layers
separately means each gets its own project UUID and those can drift between
runs, so cross-layer references and downstream queries are fragile.

Instead we now:

  1. load every kernel-valid layer (from ``sysml-project.yml`` ``layers:``) into
     the kernel, in strict import order;
  2. emit an umbrella ``package <publish_root> { import BilgePump_<layer>::*; }``
     cell that re-exports all layers; and
  3. ``%publish <publish_root>`` ONCE.

One package -> one project (``publish_root``, default ``BilgePump``).  Re-running
republishes the SAME project name, so its UUID stays stable; a republish is just
a new commit on that one project.

FORESIGHT — ADDING / CHANGING A LAYER
-------------------------------------
* New layer file  -> add it to ``layers:`` in ``sysml-project.yml`` (correct
  import order). It is loaded and folded into the umbrella automatically.
* New assertion   -> add an entry to ``bilgepump_assertions.py``. A tagged
  ``%eval`` cell is generated automatically and materialized to the DB.
Nothing in this generator needs hand-editing for either case.

ASSERTIONS
----------
After publishing, one ``%eval`` cell is emitted per entry in
``bilgepump_assertions.ASSERTIONS``.  Each cell is tagged with the assertion
metadata so ``materialize_sysml_values.py`` can read the executed outputs and
build the ``sysml_assertions`` table.  IMPORTANT: the kernel returns only the
LAST expression's result per cell, so there is exactly ONE ``%eval`` per cell.

Run (via the SysMLInfra uv env — see mons_wp1/AGENTS.md)::

    cd /home/manret/SysMLInfra && uv run python examples/bilgepump/make_publish_notebook.py
"""

from __future__ import annotations

import pathlib

import nbformat

from bilgepump_assertions import ASSERTIONS, summary

HERE = pathlib.Path(__file__).resolve().parent
NOTEBOOK = HERE / "publish.ipynb"
MANIFEST = HERE / "sysml-project.yml"


def _parse_manifest(path: pathlib.Path) -> tuple[str, list[str]]:
    """Minimal YAML reader: returns (publish_root, layers) from the manifest.

    Only the two keys this generator needs are parsed, with the same forgiving
    line-oriented logic used elsewhere in the toolchain (no PyYAML dependency).
    """
    publish_root = "BilgePump"
    layers: list[str] = []
    in_layers = False
    for raw in path.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if not s or s.startswith("#"):
            continue
        if s.startswith("publish_root:"):
            publish_root = s.split(":", 1)[1].strip().strip("\"'")
            in_layers = False
        elif s == "layers:":
            in_layers = True
        elif in_layers and s.startswith("- "):
            layers.append(s[2:].strip())
        elif in_layers and not s.startswith("- "):
            in_layers = False
    return publish_root, layers


def _package_name(filename: str) -> str:
    """Map a layer file to its declared package, e.g. Library.sysml -> BilgePump_Library."""
    return "BilgePump_" + pathlib.Path(filename).stem


INTRO = (
    "# BilgePump — unified headless publish\n",
    "\n",
    "Generated by `make_publish_notebook.py` from the `.sysml` sources and "
    "`sysml-project.yml` — **do not edit by hand**.\n",
    "\n",
    "Every layer is loaded into the SysML v2 kernel, then an umbrella package "
    "re-exports them all and is `%publish`ed **once** to the local API at "
    "`http://localhost:9000`. One package -> one project -> a **stable project "
    "UUID** across republishes.\n",
    "\n",
    "After publishing, one `%eval` cell per verification assertion is evaluated; "
    "`materialize_sysml_values.py` reads these outputs into the "
    "`sysml_assertions` table.\n",
    "\n",
    "Run headlessly with `publish_bilgepump.sh` (in `mons_wp1`).",
)


def build() -> nbformat.NotebookNode:
    publish_root, layers = _parse_manifest(MANIFEST)
    packages = [_package_name(f) for f in layers]

    nb = nbformat.v4.new_notebook()
    nb.metadata["kernelspec"] = {
        "display_name": "SysML",
        "language": "sysml",
        "name": "sysml",
    }
    nb.metadata["bilgepump"] = {
        "publish_root": publish_root,
        "layers": layers,
        "assertion_count": len(ASSERTIONS),
    }
    nb.cells.append(nbformat.v4.new_markdown_cell("".join(INTRO)))

    # 1. Load every layer into the kernel (verbatim), in import order.
    nb.cells.append(nbformat.v4.new_markdown_cell("## 1 — Load layers into the kernel"))
    for filename, package in zip(layers, packages):
        source = (HERE / filename).read_text(encoding="utf-8")
        nb.cells.append(
            nbformat.v4.new_markdown_cell(f"### `{filename}` -> `{package}`")
        )
        nb.cells.append(nbformat.v4.new_code_cell(source))

    # 2. Umbrella package that re-exports every layer, then a single publish.
    imports = "\n".join(f"    public import {pkg}::*;" for pkg in packages)
    umbrella = (
        f"package {publish_root} {{\n    private import ScalarValues::*;\n{imports}\n}}"
    )
    nb.cells.append(
        nbformat.v4.new_markdown_cell(
            f"## 2 — Umbrella package `{publish_root}` (unified single-project publish)"
        )
    )
    nb.cells.append(nbformat.v4.new_code_cell(umbrella))
    nb.cells.append(nbformat.v4.new_code_cell(f"%publish {publish_root}"))

    # 3. One %eval cell per assertion (tagged for the materializer).
    nb.cells.append(
        nbformat.v4.new_markdown_cell(
            f"## 3 — Verification assertions ({summary()})\n\n"
            "One `%eval` per cell (the kernel returns only the last expression's "
            "result). Each cell is tagged with assertion metadata read back by "
            "`materialize_sysml_values.py`."
        )
    )
    for a in ASSERTIONS:
        cell = nbformat.v4.new_code_cell(f"%eval {a['fqn']}")
        cell.metadata["assertion"] = {
            "id": a["id"],
            "fqn": a["fqn"],
            "layer": a["layer"],
            "requirement": a["requirement"],
            "kind": a["kind"],
            "expected": a["expected"],
            "note": a["note"],
        }
        nb.cells.append(cell)

    return nb


def main() -> int:
    publish_root, layers = _parse_manifest(MANIFEST)
    nb = build()
    nbformat.write(nb, NOTEBOOK)
    print(
        f"Wrote {NOTEBOOK}\n"
        f"  publish_root : {publish_root}\n"
        f"  layers       : {len(layers)} ({', '.join(layers)})\n"
        f"  assertions   : {summary()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
